### ISSUE TITLE
app mindset / structure

### ISSUE THREAD

**Issue by bbelderbos** [MartinHeroux/spike2py#2]
Pasting mindmap here to have it handy as we work through this project together:

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/387927/88797446-a10bc900-d1a3-11ea-8673-a35651211bbe.png">

So you start with the data processing side right? Please commit some files to tests/payloads

**Comment by MartinHeroux** [comment]
I have pushed the payloads, which are located in the tests folder.

1. import data
2. parse data and generate an instance of Signals() or of one of its children classes.
3. apply signal processing, either interactively in the console or Jupyter, or programmatically based on the details contained in the 'processing details' (middle purple box of the 'processing pipeline')
4. Optional: group all Signals() into a Trial(), which may contain useful attributes ('subject_id', 'trial_name', 'trial_duration', etc).

**Comment by bbelderbos** [comment]
ok cool, looking forward to the first PR with some code to review
