### ISSUE TITLE
Batch export link

### ISSUE THREAD

**Issue by joannadiong** [MartinHeroux/spike2py#2]
Hyperlinks to the Spike-to-Matlab export file don't seem to work in some places, e.g. in [Overview](https://martinheroux.github.io/spike2py/overview.html) and [Tutorial](https://martinheroux.github.io/spike2py/tutorial.html). Not sure if there are broken links in other pages? Thanks. Great package.

**Comment by MartinHeroux** [comment]
Thank you for that. I did notice the broken link in the Overview last week, but had not gotten around to fixing it. The links are now fixed.
