### ISSUE TITLE
Method chaining

### ISSUE THREAD

**Issue by MartinHeroux** [MartinHeroux/spike2py#24]
Hi Bob, 

You may have already found out all about this, but method chaining seems very simple.

[Method chaining](https://medium.com/@adamshort/python-gems-5-silent-function-chaining-a6501b3ef07e)

The one thing I am wondering about is that they are methods that are being called; that is, each of my signal processing methods have to be part of the class that I am using chaining with (i.e. Waveform). 

How would this work if I had all my signal processing methods in another class, possibly a mixin?

I guess that now leads me to wonder what the str class and others look like inside....do they have lots and lots of methods in their class? Or is there a nice way to make the methods of one class (e.g. a mixin) appear to be the methods of another class (e.g. waveform). 

I will look into this, but thought I would ask if you had any thoughts....

**Comment by bbelderbos** [comment]
Great find! 

Seems to work well with mixins too:

```
$ more calc.py
class MixinExample:
    multiplier = 10

    def multiply(self, number=None):
        number = number if number else self.multiplier
        self.number *= number
        print(self.number)
        return self


class Calculator(MixinExample):

    def __init__(self, number):
        self.number = number

    def __str__(self):
        return f"Number = {self.number}"

    @property
    def half(self):
        self.number /= 2
        print(self.number)
        return self

    @property
    def double(self):
        self.number *= 2
        print(self.number)
        return self


calc = Calculator(10)
breakpoint()
```

In the debugger:

```
(Pdb) print(calc)
Number = 10
(Pdb) calc.double.multiply()
20
200
<__main__.Calculator object at 0x7f8a8ca29820>
(Pdb) print(calc)
Number = 200
(Pdb) calc.double.multiply(9).half
400
3600
1800.0
<__main__.Calculator object at 0x7f8a8ca29820>
(Pdb) print(calc)
Number = 1800.0
```

**Comment by MartinHeroux** [comment]
Hi Bob,

I have done some good work today, and was able to have chaining working.

I initially had a mixin class with the `signal processing` methods, and this mixin class was inherited by the Waveform class. This work just as well as having the `signal processing` methods inside the Waveform class itself (as advertised).

I can see that the mixin class made the Waveform class shorter in length. Also, I guess it creates a mixin class that can be passed to other classes. However, I was not sure how I would test the various methods in the mixin.

The `self` in the mixin refers to the class that has inherited it, so creating an instance of the mixin class and `self.values` causes an error. Should the mixin methods be tested indirectly, as part of the my tests for the Waveform class? Or should I have an __init__ method that would only be used for testing purposes?

Other than this issue, I am pretty happy with the result. the chaining of methods makes for really clear and readable code, and works great with code completion. 

Once I finalise this mixin stuff and make test for all the signal processing methods, there won't be much left to get a MVP (which is pretty cool)!

**Comment by bbelderbos** [comment]
Awesome man!

"creates a mixin class that can be passed to other classes" - seems you have the design pattern right!

Ideally the mixin can be tested in isolation (as any class in general). 
Open me a PR what you have up till now if you're not sure.

Btw one downside of this chaining is debugging so use wise judgement:
https://stackoverflow.com/a/4547027
(so I am assuming that the methods you chain are unlikely to crash, right?)
