### ISSUE TITLE
Code style and type hinting

### ISSUE THREAD

**Issue by MartinHeroux** [MartinHeroux/spike2py#32]
I have heard a lot about flake8, and more recently black. 

What are your views on black? It seems like a sensible thing to further increase the look and readability of code, and there seems to be ways to include running black (and other tools) as part of the commit process. A bit over my head, but I was looking at [this post](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) on the topic.

---------------

As mentioned elsewhere, I like the idea of type hinting, but am not sure how to implement it consistently (and to what extent). 

As we work more on my code, let me know if you can see where/how I could include type hints. Should they be everywhere? Is it worth the effort?

**Comment by bbelderbos** [comment]
Yep pre-commit is cool, Patrick added it to karmabot: https://github.com/PyBites-Open-Source/karmabot/blob/master/.pre-commit-config.yaml

**Comment by bbelderbos** [comment]
Type hints, I said _defer_ in my previous note, and it does in fact depend on your time, but there are some good reasons to do it based on the fact that your package will be open source and possibly will get contributions over time:

https://realpython.com/lessons/pros-and-cons-type-hints/

> In libraries that will be used by others, especially ones published on PyPI, type hints add a lot of value. Other code using your libraries needs these type hints to be properly type checked itself. For examples of projects using type hints, see cursive_re, black, our own Real Python Reader, and Mypy itself.

> In bigger projects, type hints help you understand how types flow through your code, and are highly recommended, all the more so in projects where you cooperate with others.

**Comment by bbelderbos** [comment]
Thanks I will read that black/flake8 post. `black` is cool and I like its formatting but I somehow still use flake8 manually via my .vimrc shortcut: `autocmd FileType python map <buffer> ,f :call Flake8()<CR>` - maybe a control thing?

Putting `black` in a pre-commit hook is very tempting though.
