### ISSUE TITLE
Importing issues

### ISSUE THREAD

**Issue by MartinHeroux** [MartinHeroux/spike2py#44]
**I am a bit at a lose with the importing stuff.**
```
package/
    __init__.py
    module1.py
    module2.py
```
**I was under the impression that if `package` was part of the Python path, and `__init__.py` was empty, I should be able to do the following:**
``` python
import package
package.module1.fx_in_module1()
```
``` python
from  package import module1
module1.fx_in_module1()
```
``` python
from  package.module1 import fx_in_module1
fx_in_module1()
```
**This does not work with spike2py. I can run `import spike2py` but no modules or functions appear.**

![g](https://user-images.githubusercontent.com/12129388/90717159-453fe600-e2f2-11ea-87dd-8313f288548e.png)

**Weirdly, if I add `from . import trial` to `__init__.py`, I can run `import spike2py` and all the modules appear, not just `trial`**
![dd](https://user-images.githubusercontent.com/12129388/90717247-80dab000-e2f2-11ea-8ffb-848bc0e5e876.png)

****Similar if I use `from .trial import Trial, TrialInfo`**

**This asses these Classes, in addition to the modules. And each of the modules will include all the variables and imports (e.g. np)**

![ddd](https://user-images.githubusercontent.com/12129388/90717352-bb444d00-e2f2-11ea-9847-8ae6e186665f.png)

-------------------------------

[PEP328](https://www.python.org/dev/peps/pep-0328/)

[Similar question on stackoverflow about namespaces (like np showing up). Also talks about __all__](https://stackoverflow.com/questions/27586215/avoid-sub-modules-and-external-packages-in-a-modules-namespace)
[
Keneith Reitz on modules/package](https://docs.python-guide.org/writing/structure/#modules)

[pydocs good example with package](https://docs.python.org/3/tutorial/modules.html#packages)

**Comment by bbelderbos** [comment]
The autocomplete of other imported modules seems normal, see `requests`:

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/387927/90807494-d88f1080-e31e-11ea-97c0-b6a00390c5d5.png">

**Comment by bbelderbos** [comment]
This now matches `__init__.py` on master:

```
>>> import spike2py as sp
>>> sp.
sp.channels sp.plot     sp.read     sp.sig_proc sp.trial    sp.types
```

**Comment by bbelderbos** [comment]
Changing one module in `__init__.py` -> `from .channels import Channel, ChannelDetails, Event` this works no?

```
>>> import spike2py as sp
>>> sp.
sp.Channel(        sp.ChannelDetails( sp.channels        sp.Event(          sp.plot            sp.read            sp.sig_proc        sp.trial           sp.types
>>> sp.
```

**Comment by bbelderbos** [comment]
What I am a bit confused by is that `sp.channels` is still exposed?

**Comment by bbelderbos** [comment]
But again same for requests?

https://github.com/psf/requests/blob/master/requests/__init__.py

In spite of `from .sessions import session, Session` I can tab complete `requests.sessions.` and see all.

**Comment by MartinHeroux** [comment]
I also note that when you import requests, you can do see the following:

```python
>>> import requests
>>> requests.cookies.calendar
```
Where calendar is a built-in module that is imported in the cookies module.

Therefore, I don't see the current setup in spike2py as inappropriate.

**Comment by bbelderbos** [comment]
Yep I agree. Will you still update  `__init__.py` on a branch for more explicit imports though?

**Comment by MartinHeroux** [comment]
This has been done.
