### ISSUE TITLE
Documenation update

### ISSUE THREAD

**Issue by MartinHeroux** [MartinHeroux/spike2py#49]
Apologies! I did lots of work today and did not realise I was on the master branch.

As it is getting late I could not figure out quickly how to move all of this work to a new branch so that could push and make a pull request. 

Therefore I simply pushed it to the master branch. Thankfully, most of the changes/additions were to documentation. I have done lots of work on it and have completed the tutorial. 

Have a look: firefox (or chrome) spike2py/docs/builds/html/index.html

There is more to do, but I feel I have a good grasp of what needs to be done and I would rather move on to the next project and not spend even more time documenting the project. 

Having said this, I don't want to forget about this project because I do want to figure out how to use pre-commit hooks (black, pytest) and also how to get my package (once I finish the documentation), up on pypi.

**Comment by bbelderbos** [comment]
OK I will generate the docs and read through them later.

Good idea to move on to next project, documentation can always be improved later.

I notify you here when setup training is up, I think it will be useful for you (we're putting it in a separate coaching calls product, hence the slight delay).

Let me know if you need help on pre-commit hooks. Patrick G started using them for Karmabot, maybe you can get some inspiration here: https://github.com/PyBites-Open-Source/karmabot

**Comment by bbelderbos** [comment]
How do you generate the docs? Seems the images don't work for me:

```
(venv) [bobbelderbos@imac docs (master)]$ make html
Running Sphinx v3.2.1
making output directory... done
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 9 source files that are out of date
updating environment: [new config] 9 added, 0 changed, 0 removed
reading sources... [100%] pages/tutorials
/Users/bobbelderbos/code/PDM/projects/spike2py/spike2py/channels.py:docstring of spike2py.channels.Channel:4: WARNING: Unexpected section title or transition.

----------
/Users/bobbelderbos/code/PDM/projects/spike2py/docs/source/pages/tutorials.rst:: WARNING: image file not readable: pages/../img/tutorial_trial_plot.png
/Users/bobbelderbos/code/PDM/projects/spike2py/docs/source/pages/tutorials.rst:: WARNING: image file not readable: pages/../img/tutorial_flow_raw.png
/Users/bobbelderbos/code/PDM/projects/spike2py/docs/source/pages/tutorials.rst:: WARNING: image file not readable: pages/../img/tutorial_flow_zeroed.png
/Users/bobbelderbos/code/PDM/projects/spike2py/docs/source/pages/tutorials.rst:: WARNING: image file not readable: pages/../img/tutorial_flow_zeroed_filtered.png
/Users/bobbelderbos/code/PDM/projects/spike2py/docs/source/pages/tutorials.rst:: WARNING: image file not readable: pages/../img/tutorial_volume.png
/Users/bobbelderbos/code/PDM/projects/spike2py/docs/source/pages/tutorials.rst:: WARNING: image file not readable: pages/../img/tutorial_trial_plot_post_load.png
looking for now-outdated files... none found
```

And:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/387927/91023192-8720a300-e5f6-11ea-922b-247b5a714374.png">

**Comment by MartinHeroux** [comment]
Not sure about images. I am assuming they are actually there on your system in the `img` folder...correct? 

I used a relative import, which seemed to work on my system. Not sure how else to do it in .rst. I will look into this.

We can have a quick look on Wed to see if we can figure it out.

**Comment by bbelderbos** [comment]
Yep they are there:

```
$ ls source/img/
EMG_400x132.png			spike2py_icon.png		spike2py_icon_600x300.png	spike2py_icon_600x600.png	tutorial_diaph_smu.png
```

We'll figure it out. Overall looks great, also nice logo :)
