### ISSUE TITLE
Is it customary to delete branches once they have been merged?

### ISSUE THREAD

**Issue by MartinHeroux** [MartinHeroux/spike2py#5]
On my machine, I still have the `init` branch where I created two folders (`spike2py` and `tests`) each with an `__init__.py` file.

This branch had a pull-request logged on github and it was merged. 

Should I leave the branch there, or can I delete it? I ask this because I am assuming that we will start to have lots of branches very soon. 
If I am to delete the branch, where should this happen? On my machine, or github, or both? Or if I delete the branch in `local` will this be passed along to `origin`?

**Comment by bbelderbos** [comment]
Long story short as long as it's merged you won't lose changes and if it isn't git will warn you: https://stackoverflow.com/questions/5330145/when-to-delete-branches-in-git

By default you only delete locally, here is how to delete a remote branch:
https://stackoverflow.com/a/5330188

In practice I never delete branches locally nor remotely.

**Comment by MartinHeroux** [comment]
Thank you, and sorry for not googling it myself :(

**Comment by bbelderbos** [comment]
That is ok, I still could add my experience to that answer :)
