### ISSUE TITLE
TO DO list for spike2py - reminder of things that need to be finished

### ISSUE THREAD

**Issue by MartinHeroux** [MartinHeroux/spike2py#50]
- [x]  Create tests for aspects of plot.py that can be tested
- [x]  Create tests to confirm plots are being generated and saved
- Add how-to's to the documentation:
   - [X] For a more detailed TrialInfo prior to importing
   - [ ] For each of the methods in the sig_proc mixin class
- Topic guides
    - [X]  Why the choice to use data exported to .mat?
    - [X]  Scope: what spike2py is and what it isn't
- Update current tests
    - [x]  Have error tests use 'match' to confirm that the proper error term is being returned
    - [x]  Use ` 5.13434322311 == approx(5.1)` for testing numbers with decimal points (i.e. `approx` rather than hack I am currently using
- [x]  Look into pytest-mpl for a possible way to add tests for generated figures in matplotlib

**Comment by bbelderbos** [comment]
Sounds good, I guess that's for this week right? And start next project end of the week / next week?

**Comment by bbelderbos** [comment]
After those:
- docs autogenerate
- precommit hook for black, trailing whitespaces and maybe run tests before commit (e.g. https://github.com/PyBites-Open-Source/karmabot/blob/master/.pre-commit-config.yaml)
- PyPI upload - https://pybit.es/opensource-package-pypi.html
