### ISSUE TITLE
Including tutorial data and possible issues with pypi build

### ISSUE THREAD

**Issue by MartinHeroux** [MartinHeroux/spike2py#51]
I thought the best way to provide an error-free tutorial experience would be to ship a sample dataset with spike2py. That way everyone will be able to test their installation as well as work through the tutorial without having to have their own data.

The potential problem with this approach is  that my tests folder is beside the spike2py folder, not inside of it. I guess there are two approaches to pytest and where the tests folder is located. In reading more about pytest, etc, it seems that the current folder structure might mean that the tests folder will not be part of the package uploaded to pypi. 

This is a problem because the sample dataset is actually one of the datasets in the payload folder, which may not be included in the pypi build.

Should I consider moving the tests folder inside of the main spike2py folder (where the actual code lives)? Or should I include the sample dataset alongside (or in a `demo` folder) located in the spike2py folder with the modules?

**Comment by bbelderbos** [comment]
I think outside of the source folder is better. 

I hit the same consideration this weekend:
https://github.com/PyBites-Open-Source/pybites-tips

By specifying `packages=["pytip"],` in `setup.py` - I will upload setup demo today btw - it will not package up the test folder.

But then if somebody wants to run the tests, they would typically `git clone` your repo which pulls in the tests.

`requests` works the same:

```
(venv) [bobbelderbos@imac codechalleng.es (master)]$ ls venv/lib/python3.7/site-packages/requests/
__init__.py		_internal_utils.py	auth.py			cookies.py		hooks.py		sessions.py		utils.py
__pycache__		adapters.py		certs.py		exceptions.py		models.py		status_codes.py
__version__.py		api.py			compat.py		help.py			packages.py		structures.py
```

And:
https://github.com/psf/requests/blob/master/setup.py

(btw some other interesting things they put in setup.py)

HTH
Bob

**Comment by bbelderbos** [comment]
Now you could include them easily by adding the tests subdirectory to `packages`, but it does make your package bigger, see https://stackoverflow.com/a/32391295

What about the first option there? "Include tests in the distribution, but not install them" - so add the tests directory to `MANIFEST.in`? Would that be a good workaround?

**Comment by MartinHeroux** [comment]
I followed most of what you talked about.  I do get a bit lost looking at setup.py files, but that will come with time. I am still not clear how I should add the data file for the tutorial, but I am sure we will talk about it on Wed.

**Comment by bbelderbos** [comment]
The data file can live under payloads or you could load it in from S3. 

It's more a decision if you want to bundle up your tests in your package. They don't have to live inside your source folder for you to be able to do that. You can include the test directory in setup.py or in MANIFEST.in

We can further discuss this on our Wednesday call.

Check out the last Code Clinic about packaging and setup.py - I think you'll find it interesting:
https://members.pybit.es/products/pybites-coaching-calls-2/categories/3469727/posts/11582388
(we added the calls to a new product I just granted you access to)

**Comment by bbelderbos** [comment]
Hey @MartinHeroux, oops I forgot to post this but here is an example of how we usually pull in data for our Bite exercises:

```
# prework
# download pickle file and store it in a tmp file
pkl_file = 'pycon_videos.pkl'
data = 'https://bites-data.s3.us-east-2.amazonaws.com/{}'.format(pkl_file)
tmp = os.getenv("TMP", "/tmp")
pycon_videos = os.path.join(tmp, pkl_file)
urllib.request.urlretrieve(data, pycon_videos)
```

This gets rid of the dependency of packaging up the test folder, which as we discussed, is best left out of the package.

AWS has a great free tier, you can create an S3 bucket and upload the file there (don't forget to make it public though)

HTH
Bob

**Comment by MartinHeroux** [comment]
Hi Bob,

I signed up to AWS and updated my file. 

I have made it public (I think; I made the bucket public as well as the file; I got warned about both, but went ahead with it)
The status of the file is as follows:

![aws](https://user-images.githubusercontent.com/12129388/91393876-b137c680-e87d-11ea-8242-8c281b98a171.png)

I tried the following code:

``` python

import os
import urllib
tutorial_file = 'motor_unit.mat'
data = f'https://spike2py.s3-ap-southeast-2.amazonaws.com/{tutorial_file}'
tmp = os.getenv("TMP", "/tmp")
tutorial_data = os.path.join(tmp, tutorial_file)
urllib.request.urlretrieve(data, tutorial_file)
```

But got this error:

```python 
Traceback (most recent call last):
  File "/home/martin/anaconda3/envs/spike2py/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ddea93af5fe9>", line 7, in <module>
    urllib.request.urlretrieve(data, tutorial_file)
  File "/home/martin/anaconda3/envs/spike2py/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/martin/anaconda3/envs/spike2py/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/martin/anaconda3/envs/spike2py/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/martin/anaconda3/envs/spike2py/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/martin/anaconda3/envs/spike2py/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/martin/anaconda3/envs/spike2py/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/martin/anaconda3/envs/spike2py/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
Any suggestions what I may have done wrong?

Marty

**Comment by bbelderbos** [comment]
Yes you need to make both file and bucket public. On the file upload there is a button Make Public. On the bucket check the permissions tab, what does it say?

**Comment by MartinHeroux** [comment]
I started over (deleted everything) and selected public everywhere (see below). Personally I still can download the file. 

If you can't get it to work this could be something we solve next Wed.


![aws2](https://user-images.githubusercontent.com/12129388/91400061-65d3e700-e882-11ea-8ee7-b64687e7755c.png)
![aws](https://user-images.githubusercontent.com/12129388/91400066-679daa80-e882-11ea-80d4-747a35b62be8.png)

**Comment by bbelderbos** [comment]
Yeah not sure if you want to share login details, otherwise we do it on Wednesday, because it is not a stopper now. 

On the file you used "Make public" no?

<img width="594" alt="image" src="https://user-images.githubusercontent.com/387927/91412568-402aeb80-e84a-11ea-9339-28225b9565ff.png">

**Comment by bbelderbos** [comment]
Received your login. 

Did you do something else, because it works now:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/387927/91417531-3eb0f180-e851-11ea-8581-3d88bd343f96.png">

```
$ python data.py
$ lt /tmp/
...
-rw-r--r--  1 bobbelderbos  wheel   5.8M Aug 27 10:36 motor_units.mat

(venv) [bobbelderbos@imac 45 (master)]$ cat data.py
import os
from urllib.request import urlretrieve


tutorial_file_s3 = 'https://spike2py.s3-ap-southeast-2.amazonaws.com/motor_units.mat'
tmp = os.getenv("TMP", "/tmp")
tutorial_file_local = os.path.join(tmp, os.path.basename(tutorial_file_s3))
urlretrieve(tutorial_file_s3, tutorial_file_local)
```

**Comment by MartinHeroux** [comment]
Thanks, I included the change into demo.py and everything works now.
